# Generated by Django 3.0.3 on 2020-02-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_card_date_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
    ]
